(setq max-antworten 10)
(setq standart-antwort "Keine Ahnung")
(setq prozent-fragen 20)
(setq irc-nick "Chabotty")
(setq irc-user "Chat Bot")
(setq irc-port 6667)
(setq irc-server "irc.freenode.net")
(setq irc-channel "#chabotty")
(setq blacklist '("wer" "wie" "wo" "was" "warum" "ist" "bin" "bot"))