(setq max-antworten 10)
(setq standart-antwort "Keine Ahnung")
(setq prozent-fragen 20)
(setq irc-nick "Volldepp")
(setq irc-user "Ich bin so bloede")
(setq irc-port 6667)
(setq irc-server "irc.euirc.net")
(setq irc-channel "#hoeppi")
(setq blacklist '("wer" "wie" "wo" "was" "warum" "ist" "bin" "bot"))